[Addon]
Name=Quick Emoji
Comment=System-wide Slack-style emoji completion
Type=SharedLibrary
Library=quickemoji
Category=Module
Version=0.1.0
OnDemand=False
Configurable=False

[Addon/Dependencies]
0=core
